//@version=5
indicator("oiwr", shorttitle="oiwr", format=format.price, precision=2, timeframe="", timeframe_gaps=true)
bool isCrypto = syminfo.type == 'crypto'
var string timeframe = not isCrypto and timeframe.isintraday ? '1D' : timeframe.period

[oiOpen, oiHigh, oiLow, oiClose, oiColorCond] = request.security(str.format('{0}_OI', ticker.standard(syminfo.tickerid)), timeframe, [open, high, low, close, close > close[1]], ignore_invalid_symbol = true)

length = input(title="Length", defval=14)
src = oiClose
_pr(length) =>
	max = ta.highest(length)
	min = ta.lowest(length)
	100 * (src - max) / (max - min)
percentR = _pr(length)
obPlot = hline(-20, title="Upper Band", color=#787B86)
hline(-50, title="Middle Level", linestyle=hline.style_dotted, color=#787B86)
osPlot = hline(-80, title="Lower Band", color=#787B86)
fill(obPlot, osPlot, title="Background", color=color.rgb(126, 87, 194, 90))
plot(percentR, title="%R", color=#7E57C2)